# -*- coding: utf-8 -*-
"""Day1_SIH2020_Features.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qt3Dm78UMzy8T6gxCC1ZOQBDGBECHNrd
"""

pip install request

pip install wwo-hist

from wwo_hist import retrieve_hist_data

import os
os.chdir("")

"""# Features under exploration

- Rainfall.   - Wold weather online.com API
- Elvation    - World weather online.com API
- Humidity    - World weather online.com API
"""

frequency=24
start_date = '01-JAN-2018'
end_date = '31-DEC-2019'
api_key = '449f0a6375314d9994e140823200108'
location_list = ['Banaskantha']

hist_weather_data = retrieve_hist_data(api_key,
                                location_list,
                                start_date,
                                end_date,
                                frequency,
                                location_label = True,
                                export_csv = True,
                                store_df = True)

display(hist_weather_data)

import pandas as pd
df = pd.DataFrame(hist_weather_data)

hist_weather_data

type(hist_weather_data)

hist_weather_data[0]

